---
platform: liux

image_resource:
    type: docker-image
    source:
        repository: maven
        tag: '3.6.0-jdk-8-slim'

inputs:
- name: spring-petclinic-microservices

run:
    path: spring-petclinic-microservices/ci/tasks/unit.sh